### ISSUE TITLE
DELETE on schedules endpoint 404's

### ISSUE THREAD

**Issue by imsickofmaps** [praekelt/mama-ng-scheduler#40] opened 2015-09-07 13:34 UTC
To replicate: GET http://mama-ng-scheduler.qa.praekelt.com/mama-ng-scheduler/rest/schedules/11 responds with body, then DELETE responds with a 404 `"/WEB-INF/grails-app/views/error.gsp" not found.` This might be a template missing issue, masking a bug.

**Comment by imsickofmaps** [comment] 2015-09-10 14:02
@hodgestar can I check if this is tracked on a backlog anywhere?

**Comment by hodgestar** [comment] 2015-09-10 14:30
@imsickofmaps It's on our current sprint board under the mole-whacking card.

**Comment by hodgestar** [comment] 2015-09-24 12:03
Duplicate of #36.

**Closed as completed by hodgestar** 2015-09-24 12:03 UTC
